### ISSUE TITLE
It seems the output is limited to 10 minutes of audio

### ISSUE THREAD

**Issue by boltomli** [Azure-Samples/Cognitive-Speech-TTS#132]
Try BatchSynthesis, which support 50+ sentences, long paragraph/chapter.

Here's a sample <https://github.com/Azure-Samples/Cognitive-Speech-TTS/tree/master/CustomVoice-API-Samples/CSharp>

It seems the output is limited to 10 minutes of audio (at least using the nural option). What if I want to process a long text file, like a required reading or a chapter of a book?

_Originally posted by @phly95 in https://github.com/Azure-Samples/Cognitive-Speech-TTS/issues/128#issuecomment-529672739_

**Comment by phly95** [comment]
How long should I have to wait through
"Checking status
NotStarted..."
showing up every few seconds in the task?

I used

python voiceclient.py -key [key] -region eastus -file tts.txt -locale en-US -voiceId 2eafe49c-e4d6-4c49-be92-ba55f6ab3971 -format audio-24khz-160kbitrate-mono-mp3 --submit --concatenateResult

**Comment by phly95** [comment]
Why does it stay in the "NotStarted..." status for so long in this mode?

**Comment by phly95** [comment]
Also, is there a way to get the file later instead of leaving the command window open the whole time?

**Comment by boltomli** [comment]
> Also, is there a way to get the file later when it's finished instead of leaving the command window open the whole time?

This is related to your implementation detail. Could try create a service, call by async, run in background, etc.

**Comment by phly95** [comment]
I am a complete beginner at this, so I don't know what you mean by any of those. I'm using the python script https://github.com/Azure-Samples/Cognitive-Speech-TTS/tree/master/CustomVoice-API-Samples/Python and got this line working

python voiceclient.py -key [censored] -region eastus -file tts.txt -locale en-US -voiceId 2eafe49c-e4d6-4c49-be92-ba55f6ab3971 -format audio-24khz-160kbitrate-mono-mp3 --submit --concatenateResult

but if I'm doing this on my laptop, and I have to turn it off between classes or something, then it's just wasted because by the time it's processed, I will have lost the session.

**Comment by boltomli** [comment]
The samples are kept very simple as basic demos showing only how to call the API, and may not fit in production use.

Since the problem you are experiencing now is not directly related to the speech services, we may not provide more accurate solution yet. But it's still a good question on sites such as stackoverflow.
