### ISSUE TITLE
pt-PT and pt-BR say-as spell support issue

### ISSUE THREAD

**Issue by boltomli** [Azure-Samples/Cognitive-Speech-TTS#134]
I´m using voice **pt-PT-HeliaRUS** with language **pt_PT** for a chatbot in a project for a client.
We are facing issues when the bot speaks email addresses.
When i send this text using ssmlSpeak:

"O seu e-mail é <say-as interpret-as=\"characters\">anarebelo@sapo.pt</say-as>"

The email is not being spelled.

I tried other voices and languages like :  pt-BR-HeloisaRUS pt_BR and en-US-JessaRUS en-US.

Only in the voice "en-US-Jessa24kRUS" he spells the name.

Can you tell me why ?

By the way , we have a workaround to force spelling that is separate the email text with spaces:
"O seu e-mail é <say-as interpret-as=\"characters\">a n a r e b e l o @ s a p o . p t < / say-as>"

Is this a problem with pt-PT language? And how can i have better results spelling emails correctly ?

_Originally posted by @bodyzatva in https://github.com/Azure-Samples/Cognitive-Speech-TTS/issues/128#issuecomment-529984020_

**Comment by bodyzatva** [comment]
And the letter "o" sounds like "u" so this is not correct, it should sound like "o" .
When validating on voice something like a licence plate or an email or something else using the say as characters, the result is that the user will ear the wrong  letters.
on this example:
<say-as interpret-as="characters">a e i o u</say-as></voice></speak> 
the outcome is 
a e i u u

**Comment by yanzhenms** [comment]
"o" is usually read as "u" as an article in pt-br, so without say-as tag, it's probably not going read it correctly. When you use <say-as interpret-as="characters">, "o" is actually read as "ó", the problem is the break is too short. If you know where you'd like the words are spelled out and use the say-as tag,  I think you can also split the words and insert spaces to introduce break, it is the best solution currently.  We will fix this issue later.

**Comment by iMicknl** [comment]
@yanzhenms thanks for your response! What about `pt-PT`? How should "o" be pronounced and how is it currently pronounced.

**Comment by boltomli** [comment]
The character read fix is online now, with proper SSML. Feel free to let me know if anything is not expected.
