### ISSUE TITLE
How to use a sampling rate of 44 kHz using the REST API

### ISSUE THREAD

**Issue by hannabonert** [Azure-Samples/Cognitive-Speech-TTS#218]
Hello,
I followed the sample from [here](https://github.com/Azure-Samples/Cognitive-Speech-TTS/tree/master/PronunciationAssessment/Java/jre), and can successfully send 16 kHz audio to the service, and receive a valid response.
How can I use a sampling rate of 44100 hz?

I have tried both of the below, but I get "InitialSilenceTimeout" for every recording that I try.
connection.setRequestProperty("Content-Type", "audio/raw;encoding=signed-integer;bits=16;rate=44100");
connection.setRequestProperty("Content-Type", "audio/wav; codecs=audio/pcm; samplerate=44100");

As a test, I ran the same recording through at 16 kHz, and got a "RecognitionStatus" of "Success". I then resampled it to 44100 kHz, and I got "InitialSilenceTimeout".

I have an example using the speech SDK that works, but now I need to use 44 kHz audio data with the REST API.

Any advice would be greatly appreciated.

Thank you!

**Comment by yinhew** [comment]
Hi, @hannabonert 

Sorry for the late response.

In order to handle 44100 hz audio, you need use a different wave header.
You can change [line 53](https://github.com/Azure-Samples/Cognitive-Speech-TTS/blob/master/PronunciationAssessment/Java/jre/src/com/microsoft/cognitiveservices/pronunciationassessment/Sample.java#L53) to below:

		final byte[] WaveHeader44K16BitMono = new byte[] { 82, 73, 70, 70, 78, (byte)128, 0, 0, 87, 65, 86, 69, 102, 109, 116, 32, 18, 0, 0, 0, 1, 0, 1, 0, 68, (byte)172, 0, 0, 0, (byte)136, 88, 0, 2, 0, 16, 0, 0, 0, 100, 97, 116, 97, 0, 0, 0, 0 };

And then update [line 78](https://github.com/Azure-Samples/Cognitive-Speech-TTS/blob/master/PronunciationAssessment/Java/jre/src/com/microsoft/cognitiveservices/pronunciationassessment/Sample.java#L78) to below:

		outputStream.write(WaveHeader44K16BitMono);

Let me know if this still doesn't work for you.

Thanks,
Yinhe

**Comment by hannabonert** [comment]
Thank you so much for this answer!
I will try it out.

Is there a way to change the "InitialSilenceTimeout" value using the REST API?
________________________________
