### ISSUE TITLE
Neural voices

### ISSUE THREAD

**Issue by shoutbomb** [Azure-Samples/Cognitive-Speech-TTS#95]
Attempting to use php to test the Neural voices now available:
Region | Endpoint
East US | https://eastus.tts.speech.microsoft.com/cognitiveservices/v1

Created a resource in East US and generated a key and adjusted the following:
- $AccessTokenUri = "https://eastus.api.cognitive.microsoft.com/sts/v1.0/issueToken";
- $apiKey = "provided my key here";
- $ttsServiceUri = "https://eastus.tts.speech.microsoft.com/cognitiveservices/v1";//EAST
- $voice->setAttribute( "name" , "Microsoft Server Speech Text to Speech Voice (en-US, JessaNeural)" );
- $text = $doc->createTextNode("Hello, this is the Howell library, with an announcement.");

The request return:
Warning: file_get_contents(https://eastus.tts.speech.microsoft.com/cognitiveservices/v1): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized

Have you been successful in rendering TTS using the Neural voice?

**Comment by boltomli** [comment]
Hi there, I'm able to get it work. Since Jessa is a female voice, I changed `$voice->setAttribute( "xml:gender" , "Female" );` also. Please have a try.

Do you have access token printed well? It might be because the key you use is not the latest speech type. Get the key from <https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started>.

**Comment by shoutbomb** [comment]
Appreciate your time.  It seems that for my resource the API Type needed to be "speech" not "All Cognitive Services".  I deleted my resource and created one for "speech". 
Please close this ticket.
